logging:
  file:
    name: logs/application.log
  level:
    root: INFO
  pattern:
    file: '"%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"'

spring:
  datasource:
    url: jdbc:h2:file:./launcher;TRACE_LEVEL_FILE=0;TRACE_LEVEL_SYSTEM_OUT=1;MV_STORE=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    hikari:
      maximum-pool-size: 1
  jmx:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
  main:
    banner-mode: off
    web-application-type: none

application:
  version: 3.0.3
  platform: WINDOWS
  server:
    address: mfr.fullrest.ru
    tcpPort: 9020
  #    address: mfr-beta.lezenford.com
  game-folder: game
  readme: Manual\readme\index.html
  social:
    forum: https://www.fullrest.ru/forum/forum/300-morrowind-fullrest-repack-i-drugie-proekty-ot-ela/
    discord: https://discord.gg/j2wrYTm
    youtube: https://www.youtube.com/channel/UCY0V-oKZPvv_SEnH5N8onSQ
    vk: https://vk.com/club198345102
    patreon: https://www.patreon.com/aLMFR
game:
  optional: Optional
  versionFile: Optional\version
  classic:
    application: Morrowind.exe
    launcher: Morrowind Launcher.exe
    mcp: Morrowind Code Patch.exe
    mge:
      application: MGEXEgui.exe
      folder: mge3
      config-backup: mge3\backup\MGE.ini
      config: mge3\MGE.ini
      templates:
        high: Optional\MGE\top_PC\MGE.ini
        middle: Optional\MGE\mid_PC\MGE.ini
        low: Optional\MGE\low_PC\MGE.ini
        basic: Optional\MGE\necro_PC\MGE.ini
  openMw:
    application: OpenMW\openmw.exe
    launcher: OpenMW\openmw-launcher.exe
    config-folder: documents\My Games\OpenMW
    config-backup-folder: OpenMW\OpenMW_Config\backup
    config-change-value: D:\Games\MFR\game
    templates:
      high: OpenMW\OpenMW_Config\top_PC
      middle: OpenMW\OpenMW_Config\mid_PC
      low: OpenMW\OpenMW_Config\low_PC
      basic: OpenMW\OpenMW_Config\necro_PC
