/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lezenford.mfr.launcher.model.dto


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param host 
 * @param files 
 * @param schema 
 */
@Serializable

data class GameSchemaResponse (

    @SerialName(value = "host")
    val host: String,

    @SerialName(value = "files")
    val files: String,

    @SerialName(value = "schema")
    val schema: String,

    @SerialName(value = "compressed_files")
    val compressedFiles: String? = null,

    @SerialName(value = "compressed_schema")
    val compressedSchema: String? = null

) {


}

