/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lezenford.mfr.launcher.model.dto


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param host 
 * @param launcherStorage 
 * @param jdk 
 * @param jdkStorage 
 */
@Serializable

data class LauncherSchemaResponse (

    @SerialName(value = "host")
    val host: String,

    @SerialName(value = "launcher_storage")
    val launcherStorage: String,

    @SerialName(value = "jdk")
    val jdk: String,

    @SerialName(value = "jdk_storage")
    val jdkStorage: String

) {


}

