/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lezenford.mfr.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param host 
 * @param files 
 * @param schema 
 */
@Serializable

data class VersionSchemaResponse (

    @SerialName(value = "host")
    val host: kotlin.String,

    @SerialName(value = "files")
    val files: kotlin.String,

    @SerialName(value = "schema")
    val schema: kotlin.String

) {


}

